<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <RootNamespace>CAD_ET_HANS.App</RootNamespace>
    <AssemblyName>CAD_ET_HANS</AssemblyName>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CAD_ET_HANS.Core\CAD_ET_HANS.Core.csproj" />
  </ItemGroup>

</Project>
